# This is a basic workflow to help you get started with Actions

name: CI

on:
  schedule:
    - cron: "*/5 * * * *"  # scheduled at 06:00 (UTC+8) everyday
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: echo Hello, world!
