# This is a basic workflow to help you get started with Actions

name: CI

on:
  schedule:
    - cron: "0 4,16 * * *"
  workflow_dispatch:
env:
  RUN_ENV: 'prod'
  TZ: 'Asia/Shanghai'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run start
        run: |
          python -m pip install --upgrade pip
          pip install requests
          python3 ./main.py
